source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'sqlite3'
gem 'has_secure_token'
gem 'pry'
gem 'pry-byebug'
gem 'json'
gem 'haml'
gem 'rake'
gem 'spreadsheet'
